apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuburner
  labels:
    app: cpuburner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpuburner
  template:
    metadata:
      labels:
        app: cpuburner
    spec:
      containers:
      - name: cpuburner
        image: busybox
        args: [/bin/sh, -c, 'dd if=/dev/zero of=/dev/null']
      - name: busybox
        image: busybox
        args: [/bin/sh, -c, 'while true; do echo "$(date)": $(hostname): busybox; sleep 1; done']
