apiVersion: v1 
kind: Pod 
metadata:
  name: pod-configmap-env
spec:
  containers:
    - name: mongodb
      image: mongo:4.0.4
      envFrom:
        - configMapRef:
            name: mongodb-configmap
