apiVersion: v1 
kind: Pod 
metadata:
  name: pod-env-var 
spec:
  containers:
    - name: env-var-configmap
      image: mongo
      envFrom:
        - configMapRef:
            name: mongodb-configmap