apiVersion: v1 
kind: Pod 
metadata: 
 name: pod-configmap-vol 
spec: 
 volumes: 
 - name: configmap-volume 
   configMap: 
    name: mongodb-configmap  
 containers: 
 - name: mongodb 
   image: mongo:4.0.4 
   volumeMounts: 
    - name: configmap-volume 
      mountPath: /etc/config 
