apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-not-ready
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-not-ready
  template:
    metadata:
      labels:
        app: nginx-not-ready
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
          initialDelaySeconds: 15
          timeoutSeconds: 2 # Default is 1
          periodSeconds: 5 # Default is 10
          failureThreshold: 1 # Default is 3