apiVersion: v1
kind: Pod
metadata:
  name: liveness-startup-http
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - name: liveness-port
      containerPort: 8080
      hostPort: 8080
    startupProbe:
     httpGet:
      path: /healthz
      port: liveness-port
     failureThreshold: 15
     periodSeconds: 5
    livenessProbe:
     httpGet:
      path: /healthz
      port: liveness-port
     failureThreshold: 1
     periodSeconds: 10