apiVersion: v1
kind: Pod 
metadata: 
 name: pod-secret-vol 
spec: 
 volumes: 
 - name: api-secret-volume 
   secret: 
    secretName: api-authentication-secret 
 containers: 
 - name: mongodb 
   image: mongo:latest
   volumeMounts: 
    - name: api-secret-volume 
      mountPath: /etc/secret 