kind: Pod 
apiVersion: v1 
metadata: 
 name: pod-secret-vol 
spec: 
 volumes: 
  - name: api-secret-volume 
    secret: 
     secretName: api-authentication-secret 
 containers: 
  - name: mongodb-secret 
    image: mongodb:4.0.4
    volumeMounts: 
    - name: api-secret-volume 
      mountPath: /etc/secret 