apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-busybox
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: c1
        image: busybox
        args: [/bin/sh, -c, 'while true; do echo "$(date)": $(hostname): c1; sleep 1; done']
      - name: c2
        image: busybox
        args: [/bin/sh, -c, 'while true; do echo "$(date)": $(hostname): c2; sleep 1; done']
